### ISSUE TITLE
Wrapper API

### ISSUE THREAD

**Issue by Dwaynekj** [vaughankg/biro#3]
``` js
ideaAPI.add_text_section("Hello world.");
ideaAPI.add_text_section("Coffee, eggs and bacon.");
ideaAPI.animate
```

OR

``` js
ideaAPI.add_text_section_a("Hello world.");
ideaAPI.add_text_section_b("Coffee, eggs and bacon.");
ideaAPI.animate
```

OR

``` js
ideaAPI.addTuple("Hello world", "Coffee, eggs and bacon");
ideaAPI.animate
```

**Comment by vaughankg** [comment]
How about

``` js
biro.add('key_a', 'Hello');
biro.add('World'); // You don't need to supply a key
biro.add('referendum', 'No Thanks');

biro.transition(); // Transitions to the next text. i.e. from 'Hello' to 'World'
// or
biro.transition('referendum') // Transitions to the specified key e.g. 'No Thanks'
```

**Comment by vaughankg** [comment]
We should support multiple sections/canvases on a page so we'll need a way to select them.

Ideas:

``` js
biro.section('section_a').add('Hello');
biro.section('section_b').add('Hello');
// or since we will always be operating on a section we could cut to the chase ...
biro('section_a').add('Hello');
```

**Comment by Dwaynekj** [comment]
I vote for 

``` js
biro.section('section_b').add('Hello', 'World'); //Simplest to understand
```

Best to be explicit. I's easier to go to an implicit meaning later on. Not necessarily the other way around.

BTW. 'add' implies you can add multiple per section/canvas. Maybe call it set?

As for

``` js
biro.transition(); // Transitions to the next text. i.e. from 'Hello' to 'World'
// or
biro.transition('referendum')
```

I think no args would be best understood as all canvases and otherwise specify a section.

**Comment by vaughankg** [comment]
Yeah so I'm thinking you can have multiple texts per section. Say we have 3 sets of text A, B and C and we start off with A. Then you can transition to either B or C. This is done either by transitioning to the next one in the list i.e. from A to B or by specifying which one we want to transition to. We can specify by calling the transition function with a key.

so

Add the sets of text to the section

``` js
biro.section('a_section').add('A', 'Hello'); // 'A' is the key and 'Hello' is the text
biro.section('a_section').add('B', 'Cruel');
biro.section('a_section').add('C', 'World');
```

Then under the hood we have a hash-like object looking like this:
`{ 'A': 'Hello', 'B': 'Cruel', 'C': 'World' }`

Given we are starting with `'A': 'Hello'`

``` js
biro.section('a_section').transition('B');
```

Will transition 'Hello' into 'Cruel'

**Comment by Dwaynekj** [comment]
Sounds good. Lets move forward with that
